
import type { Category, Collection, Tool, NewsItem } from "@/lib/types";
import { Bot, Code, ImageIcon, Mic, Pencil, Video, BrainCircuit, Presentation, Zap } from "lucide-react";

export const categories: Category[] = [
  { id: 'text-generation', name: 'Text Generation', description: 'Advanced LLMs for writing and reasoning.', icon: Pencil },
  { id: 'image-generation', name: 'Image Generation', description: 'Create photorealistic or artistic visuals.', icon: ImageIcon },
  { id: 'code-assistant', name: 'Code Assistant', description: 'AI-powered IDEs and pair programmers.', icon: Code },
  { id: 'audio-tools', name: 'Audio Tools', description: 'Generate music and realistic speech.', icon: Mic },
  { id: 'video-creation', name: 'Video Creation', description: 'Generate cinematic videos from text.', icon: Video },
  { id: 'chatbots', name: 'Chatbots', description: 'Conversational agents for any task.', icon: Bot },
  { id: 'research-assistant', name: 'Research Assistant', description: 'Tools for semantic search and deep research.', icon: BrainCircuit },
  { id: 'presentation-tools', name: 'Presentation Tools', description: 'Generate slides and decks instantly.', icon: Presentation },
  { id: 'productivity', name: 'Productivity', description: 'Automate your daily workflows.', icon: Zap },
];

const generateLogo = (name: string, color: string = '309554') => 
  `https://placehold.co/400x400/${color}/white.png?text=${encodeURIComponent(name.split(' ')[0].substring(0,2).toUpperCase())}`;

const generateScreenshot = (name: string) => 
  `https://placehold.co/1200x800/333/white.png?text=${encodeURIComponent(name)}+Preview`;

export const tools: Tool[] = [
  // --- Text Generation ---
  {
    id: "claude-3-5",
    name: "Claude 3.5 Sonnet",
    description: "The world's most intelligent LLM.",
    longDescription: "Claude 3.5 Sonnet sets new industry benchmarks for reasoning and coding proficiency. It is significantly better at understanding nuance and complex instructions.",
    category: "text-generation",
    logo: generateLogo("Claude", "FF5733"),
    link: "https://claude.ai",
    videoDemo: "https://www.youtube.com/embed/d-84ZqhX8WQ",
    screenshots: [generateScreenshot("Claude 3.5")],
    launchDate: "2024-06-20T00:00:00Z",
    lastUpdated: "2025-01-15T00:00:00Z",
    isTrending: true,
    toolOfTheDay: true,
    pricing: { model: "Freemium", details: "Free daily limits. Pro at $20/mo.", isPriceReduced: true },
    features: ["Advanced Coding", "Vision Capabilities", "Artifacts UI"],
    reviews: [],
    collections: ["dev-stack"],
    noCode: true,
  },
  {
    id: "openai-o3",
    name: "OpenAI o3-mini",
    description: "New reasoning model for complex logic.",
    longDescription: "o3-mini is part of OpenAI's new reasoning series, optimized for STEM and coding tasks.",
    category: "text-generation",
    logo: generateLogo("OpenAI", "10A37F"),
    link: "https://openai.com",
    screenshots: [generateScreenshot("OpenAI o3")],
    launchDate: "2025-01-31T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "Available for Plus users." },
    features: ["Chain-of-thought", "Expert Math", "Logic Reasoning"],
    reviews: [],
    collections: ["best-of-2025"],
    noCode: true,
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    description: "Ultra-efficient open-source LLM.",
    longDescription: "DeepSeek-V3 is a strong Mixture-of-Experts model that rivals top-tier proprietary models.",
    category: "text-generation",
    logo: generateLogo("DeepSeek", "2D5CF7"),
    link: "https://deepseek.com",
    screenshots: [generateScreenshot("DeepSeek")],
    launchDate: "2024-12-26T00:00:00Z",
    lastUpdated: "2025-02-10T00:00:00Z",
    isTrending: true,
    pricing: { model: "Free", details: "Free API tier available." },
    features: ["Open Source", "High Efficiency", "Coding Pro"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "grok-3",
    name: "Grok-3",
    description: "X's most powerful AI model.",
    longDescription: "Grok-3 is designed to have real-time access to the world via the X platform.",
    category: "text-generation",
    logo: generateLogo("Grok", "000000"),
    link: "https://x.ai",
    screenshots: [generateScreenshot("Grok 3")],
    launchDate: "2025-02-18T00:00:00Z",
    lastUpdated: "2025-02-18T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "Requires X Premium+." },
    features: ["Real-time Data", "Unfiltered AI", "Advanced Reasoning"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "mistral-large-3",
    name: "Mistral Large 3",
    description: "Europe's leading AI model.",
    longDescription: "The latest flagship model from Mistral AI with top-tier reasoning and multilingual support.",
    category: "text-generation",
    logo: generateLogo("Mistral", "FF5722"),
    link: "https://mistral.ai",
    screenshots: [generateScreenshot("Mistral")],
    launchDate: "2025-01-10T00:00:00Z",
    lastUpdated: "2025-01-10T00:00:00Z",
    isTrending: false,
    pricing: { model: "Paid", details: "Usage based API." },
    features: ["Multilingual", "Large Context", "Sovereign AI"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "gemini-2-ultra",
    name: "Gemini 2.0 Ultra",
    description: "Google's most capable AI model.",
    longDescription: "Gemini 2.0 Ultra is designed for massive scale and complex reasoning across text, code, images, and audio.",
    category: "text-generation",
    logo: generateLogo("Gemini", "4285F4"),
    link: "https://gemini.google.com",
    screenshots: [generateScreenshot("Gemini 2")],
    launchDate: "2025-02-01T00:00:00Z",
    lastUpdated: "2025-02-20T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "Free via AI Studio. Gemini Advanced for $20/mo." },
    features: ["Multi-modal", "Long Context (2M+)", "Google Workspace Integration"],
    reviews: [],
    collections: ["best-of-2025"],
    noCode: true,
  },

  // --- Image Generation ---
  {
    id: "flux-2",
    name: "FLUX.2 Pro",
    description: "Photorealistic image generation.",
    longDescription: "FLUX.2 Pro pushes the boundaries of text-to-image with incredible detail and prompt adherence.",
    category: "image-generation",
    logo: generateLogo("Flux", "E91E63"),
    link: "https://blackforestlabs.ai",
    screenshots: [generateScreenshot("Flux 2")],
    launchDate: "2025-02-05T00:00:00Z",
    lastUpdated: "2025-02-20T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "Credit based system." },
    features: ["Hyper-realism", "Text-in-image", "Fast Gen"],
    reviews: [],
    collections: ["best-of-2025"],
    noCode: true,
  },
  {
    id: "midjourney-v7",
    name: "Midjourney V7",
    description: "The gold standard for artistic AI.",
    longDescription: "Midjourney V7 introduces massive improvements in lighting, textures, and composition.",
    category: "image-generation",
    logo: generateLogo("Midjourney", "333333"),
    link: "https://midjourney.com",
    screenshots: [generateScreenshot("Midjourney")],
    launchDate: "2025-03-01T00:00:00Z",
    lastUpdated: "2025-03-01T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "$10/mo starting." },
    features: ["Artistic Style", "Web UI", "Discord Integration"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "ideogram-3",
    name: "Ideogram 3",
    description: "Perfect typography in AI images.",
    longDescription: "Ideogram 3 is the leader in rendering clear text within generated images.",
    category: "image-generation",
    logo: generateLogo("Ideogram", "FF4081"),
    link: "https://ideogram.ai",
    screenshots: [generateScreenshot("Ideogram")],
    launchDate: "2025-01-20T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: false,
    pricing: { model: "Freemium", details: "Free daily credits." },
    features: ["Typography", "Graphic Design", "Fast rendering"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "dalle-4",
    name: "DALL-E 4",
    description: "Next-gen creative partner from OpenAI.",
    longDescription: "DALL-E 4 focuses on complex prompt understanding and perfect object placement.",
    category: "image-generation",
    logo: generateLogo("Dalle", "10A37F"),
    link: "https://openai.com",
    screenshots: [generateScreenshot("DALL-E 4")],
    launchDate: "2025-04-15T00:00:00Z",
    lastUpdated: "2025-02-01T00:00:00Z",
    isTrending: false,
    pricing: { model: "Paid", details: "Part of ChatGPT Plus." },
    features: ["In-painting", "Creative Reasoning", "Chat-based editing"],
    reviews: [],
    collections: [],
    noCode: true,
  },

  // --- Code Assistant ---
  {
    id: "cursor",
    name: "Cursor",
    description: "The AI Code Editor.",
    longDescription: "Built on top of VS Code, Cursor is an AI-native editor that understands your whole codebase.",
    category: "code-assistant",
    logo: generateLogo("Cursor", "0078D4"),
    link: "https://cursor.com",
    videoDemo: "https://www.youtube.com/embed/Z6X7v2zX8zQ",
    screenshots: [generateScreenshot("Cursor Editor")],
    launchDate: "2023-05-10T00:00:00Z",
    lastUpdated: "2025-02-20T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "Free tier available. $20/mo Pro.", isPriceReduced: true },
    features: ["Codebase Indexing", "Composer", "Terminal AI"],
    reviews: [],
    collections: ["dev-stack"],
    noCode: false,
  },
  {
    id: "devin",
    name: "Devin AI",
    description: "The first AI software engineer.",
    longDescription: "Devin can build and deploy apps end-to-end, solving engineering tasks autonomously.",
    category: "code-assistant",
    logo: generateLogo("Devin", "607D8B"),
    link: "https://cognition-labs.com",
    screenshots: [generateScreenshot("Devin")],
    launchDate: "2024-03-12T00:00:00Z",
    lastUpdated: "2025-01-20T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "Enterprise pricing." },
    features: ["Autonomous Coding", "Real-time Debugging", "Full-stack Ops"],
    reviews: [],
    collections: ["dev-stack"],
    noCode: false,
  },
  {
    id: "replit-agent",
    name: "Replit Agent",
    description: "Build apps just by describing them.",
    longDescription: "Replit Agent handles the entire setup, coding, and deployment process in your browser.",
    category: "code-assistant",
    logo: generateLogo("Replit", "F26622"),
    link: "https://replit.com",
    screenshots: [generateScreenshot("Replit Agent")],
    launchDate: "2024-09-01T00:00:00Z",
    lastUpdated: "2025-02-10T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "Requires Replit Core subscription." },
    features: ["Natural Language to App", "Hosted Environment", "Instant Deployment"],
    reviews: [],
    collections: ["dev-stack"],
    noCode: true,
  },

  // --- Video Creation ---
  {
    id: "sora",
    name: "OpenAI Sora",
    description: "Cinematic video AI.",
    longDescription: "Sora can create videos up to a minute long while maintaining visual quality.",
    category: "video-creation",
    logo: generateLogo("Sora", "FF9800"),
    link: "https://openai.com/sora",
    videoDemo: "https://www.youtube.com/embed/mSuvIDHSrqQ",
    screenshots: [generateScreenshot("OpenAI Sora")],
    launchDate: "2025-02-15T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "Premium only." },
    features: ["1-minute videos", "Consistent characters", "Physically accurate"],
    reviews: [],
    collections: ["best-of-2025"],
    noCode: true,
  },
  {
    id: "runway-gen-4",
    name: "Runway Gen-4",
    description: "Professional AI film tools.",
    longDescription: "Gen-4 introduces advanced physics and lighting control for filmmakers.",
    category: "video-creation",
    logo: generateLogo("Runway", "000000"),
    link: "https://runwayml.com",
    screenshots: [generateScreenshot("Runway Gen-4")],
    launchDate: "2025-03-10T00:00:00Z",
    lastUpdated: "2025-03-10T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "Subscription based." },
    features: ["Motion Brush", "Multi-camera Control", "4K Rendering"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "pika-3",
    name: "Pika 3.0",
    description: "The easiest way to animate.",
    longDescription: "Pika 3.0 makes professional animation accessible to anyone with simple text prompts.",
    category: "video-creation",
    logo: generateLogo("Pika", "FFD700"),
    link: "https://pika.art",
    screenshots: [generateScreenshot("Pika")],
    launchDate: "2025-01-25T00:00:00Z",
    lastUpdated: "2025-02-18T00:00:00Z",
    isTrending: false,
    pricing: { model: "Freemium", details: "Free daily credits." },
    features: ["Lip Sync", "Sound Effects", "Stylization"],
    reviews: [],
    collections: [],
    noCode: true,
  },

  // --- Audio & Music ---
  {
    id: "udio-v2",
    name: "Udio V2",
    description: "Pro-quality AI music.",
    longDescription: "Udio V2 produces radio-ready songs in seconds with stunning vocal and instrumental quality.",
    category: "audio-tools",
    logo: generateLogo("Udio", "F44336"),
    link: "https://udio.com",
    screenshots: [generateScreenshot("Udio")],
    launchDate: "2025-01-10T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "Free plan with limited songs." },
    features: ["Radio-ready Audio", "Full Length Tracks", "Remix mode"],
    reviews: [],
    collections: ["best-of-2025"],
    noCode: true,
  },
  {
    id: "elevenlabs-v3",
    name: "ElevenLabs V3",
    description: "The most realistic AI voices.",
    longDescription: "ElevenLabs V3 introduces emotional depth and perfect multilingual synchronization.",
    category: "audio-tools",
    logo: generateLogo("Eleven", "212121"),
    link: "https://elevenlabs.io",
    screenshots: [generateScreenshot("ElevenLabs")],
    launchDate: "2024-11-01T00:00:00Z",
    lastUpdated: "2025-02-25T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "Free for hobbyists. $5/mo Starter." },
    features: ["Speech-to-Speech", "Instant Voice Cloning", "Sound Effects Gen"],
    reviews: [],
    collections: [],
    noCode: true,
  },

  // --- Research Assistant ---
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "The AI search engine.",
    longDescription: "Perplexity combines LLMs with live search to provide cited answers to any question.",
    category: "research-assistant",
    logo: generateLogo("Perplexity", "009688"),
    link: "https://perplexity.ai",
    screenshots: [generateScreenshot("Perplexity")],
    launchDate: "2022-12-01T00:00:00Z",
    lastUpdated: "2025-02-25T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "Pro at $20/mo.", isPriceReduced: true },
    features: ["Live Web Search", "Citations", "Pro Reasoning"],
    reviews: [],
    collections: ["dev-stack"],
    noCode: true,
  },
  {
    id: "consensus-v2",
    name: "Consensus",
    description: "Evidence-based research search.",
    longDescription: "Consensus searches millions of scientific papers to provide answers based on real evidence.",
    category: "research-assistant",
    logo: generateLogo("Consensus", "00B8D9"),
    link: "https://consensus.app",
    screenshots: [generateScreenshot("Consensus")],
    launchDate: "2023-01-10T00:00:00Z",
    lastUpdated: "2025-01-20T00:00:00Z",
    isTrending: false,
    pricing: { model: "Freemium", details: "Free searches available." },
    features: ["Scientific Citations", "Consensus Meter", "Auto-summaries"],
    reviews: [],
    collections: [],
    noCode: true,
  },

  // --- Productivity ---
  {
    id: "notion-ai-pro",
    name: "Notion AI",
    description: "Your connected assistant in Notion.",
    longDescription: "Notion AI helps you write, brainstorm, and summarize directly in your workspace.",
    category: "productivity",
    logo: generateLogo("Notion", "000000"),
    link: "https://notion.so/ai",
    screenshots: [generateScreenshot("Notion AI")],
    launchDate: "2023-02-20T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "$10/mo add-on." },
    features: ["Q&A", "Auto-filling", "Document Translation"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "zapier-central",
    name: "Zapier Central",
    description: "Teach AI to do your work.",
    longDescription: "Central allows you to create AI agents that can perform actions across 6000+ apps.",
    category: "productivity",
    logo: generateLogo("Zapier", "FF4A00"),
    link: "https://zapier.com/central",
    screenshots: [generateScreenshot("Zapier Central")],
    launchDate: "2024-03-01T00:00:00Z",
    lastUpdated: "2025-02-01T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "Free during beta." },
    features: ["No-code Agents", "Multi-app Workflows", "Live Data Access"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  
  // --- Adding More for Total of 40+ ---
  {
    id: "llama-4-70b",
    name: "Llama 4",
    description: "Meta's next-gen open source giant.",
    longDescription: "The latest Llama model setting the bar for open-weight intelligence.",
    category: "text-generation",
    logo: generateLogo("Llama", "0467DF"),
    link: "https://llama.meta.com",
    screenshots: [generateScreenshot("Llama 4")],
    launchDate: "2025-05-01T00:00:00Z",
    lastUpdated: "2025-02-01T00:00:00Z",
    isTrending: false,
    pricing: { model: "Free", details: "Open weights." },
    features: ["Open Source", "High Performance", "Massive Context"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "suno-v5",
    name: "Suno V5",
    description: "The future of AI songcraft.",
    longDescription: "Even more realistic vocals and complex musical structures.",
    category: "audio-tools",
    logo: generateLogo("Suno", "9C27B0"),
    link: "https://suno.com",
    screenshots: [generateScreenshot("Suno 5")],
    launchDate: "2025-06-15T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: false,
    pricing: { model: "Freemium", details: "Subscription based." },
    features: ["Full Songs", "Custom Lyrics", "Studio Quality"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "gamma-app",
    name: "Gamma",
    description: "AI-powered presentations and docs.",
    longDescription: "Create beautiful presentations, websites, and documents in seconds.",
    category: "presentation-tools",
    logo: generateLogo("Gamma", "3F51B5"),
    link: "https://gamma.app",
    screenshots: [generateScreenshot("Gamma")],
    launchDate: "2023-08-01T00:00:00Z",
    lastUpdated: "2025-02-20T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "$15/mo for Pro." },
    features: ["Instant Decks", "Responsive Sites", "AI Image Gen"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "tome-ai-pro",
    name: "Tome",
    description: "Generative storytelling for teams.",
    longDescription: "Tome uses AI to generate narratives and visual slides for business storytelling.",
    category: "presentation-tools",
    logo: generateLogo("Tome", "000000"),
    link: "https://tome.app",
    screenshots: [generateScreenshot("Tome")],
    launchDate: "2022-12-15T00:00:00Z",
    lastUpdated: "2025-01-10T00:00:00Z",
    isTrending: false,
    pricing: { model: "Paid", details: "Enterprise focused." },
    features: ["DALL-E Integration", "Dynamic Tiles", "Mobile Responsive"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "slides-ai-io",
    name: "SlidesAI",
    description: "Convert text to slides.",
    longDescription: "Instantly transform long articles or summaries into presentation decks.",
    category: "presentation-tools",
    logo: generateLogo("Slides", "4285F4"),
    link: "https://slidesai.io",
    screenshots: [generateScreenshot("SlidesAI")],
    launchDate: "2023-03-01T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: false,
    pricing: { model: "Freemium", details: "Free tier for students." },
    features: ["Text to PPT", "Multi-language", "Template engine"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "superhuman-ai",
    name: "Superhuman AI",
    description: "The fastest email experience.",
    longDescription: "AI that drafts your emails, summarizes threads, and schedules meetings.",
    category: "productivity",
    logo: generateLogo("Super", "000000"),
    link: "https://superhuman.com",
    screenshots: [generateScreenshot("Superhuman")],
    launchDate: "2023-06-01T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "$30/mo subscription." },
    features: ["Auto-drafting", "Instant Summaries", "Snippet expansion"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "character-ai-2",
    name: "Character.ai 2.0",
    description: "Talk to anyone, real or imagined.",
    longDescription: "New conversational engine with improved memory and emotional intelligence.",
    category: "chatbots",
    logo: generateLogo("Character", "F44336"),
    link: "https://character.ai",
    screenshots: [generateScreenshot("Character.ai")],
    launchDate: "2024-12-01T00:00:00Z",
    lastUpdated: "2025-02-10T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "c.ai+ for $10/mo." },
    features: ["Persona creation", "Group chats", "Voice calls"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "poe-by-quora",
    name: "Poe",
    description: "Your gateway to all LLMs.",
    longDescription: "Access ChatGPT, Claude, Llama, and more in one unified interface.",
    category: "chatbots",
    logo: generateLogo("Poe", "B00020"),
    link: "https://poe.com",
    screenshots: [generateScreenshot("Poe")],
    launchDate: "2023-02-01T00:00:00Z",
    lastUpdated: "2025-02-20T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "Subscription for high-end models." },
    features: ["Bot Creation", "Multi-model switch", "Web and Mobile"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "inflection-pi",
    name: "Pi by Inflection",
    description: "A kind and supportive AI.",
    longDescription: "Pi is designed to be a personal assistant that is conversational, friendly, and helpful.",
    category: "chatbots",
    logo: generateLogo("Pi", "000000"),
    link: "https://pi.ai",
    screenshots: [generateScreenshot("Pi")],
    launchDate: "2023-05-01T00:00:00Z",
    lastUpdated: "2025-01-15T00:00:00Z",
    isTrending: false,
    pricing: { model: "Free", details: "Completely free." },
    features: ["Empathetic AI", "Voice Interaction", "Daily check-ins"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "scite-ai",
    name: "scite",
    description: "See if research is supported or contrasted.",
    longDescription: "scite helps you discover and evaluate scientific articles via Smart Citations.",
    category: "research-assistant",
    logo: generateLogo("Scite", "2D3436"),
    link: "https://scite.ai",
    screenshots: [generateScreenshot("scite")],
    launchDate: "2021-05-01T00:00:00Z",
    lastUpdated: "2025-01-20T00:00:00Z",
    isTrending: false,
    pricing: { model: "Paid", details: "For researchers and institutions." },
    features: ["Citation Context", "Reference verification", "Journal rankings"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "elicit-pro",
    name: "Elicit",
    description: "The AI Research Assistant.",
    longDescription: "Elicit uses language models to help you automate research workflows like summarizing papers.",
    category: "research-assistant",
    logo: generateLogo("Elicit", "6554C0"),
    link: "https://elicit.org",
    screenshots: [generateScreenshot("Elicit")],
    launchDate: "2021-10-01T00:00:00Z",
    lastUpdated: "2025-02-05T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "$12/mo for Plus." },
    features: ["Paper Extraction", "Review matrix", "Auto-citation"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "heygen-v3",
    name: "HeyGen 3.0",
    description: "Realistic AI avatars for video.",
    longDescription: "Translate your videos into 40+ languages with perfect lip-syncing and tone matching.",
    category: "video-creation",
    logo: generateLogo("HeyGen", "FF4B5C"),
    link: "https://heygen.com",
    screenshots: [generateScreenshot("HeyGen")],
    launchDate: "2023-01-01T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: true,
    pricing: { model: "Paid", details: "Enterprise and Pro plans." },
    features: ["Instant Avatars", "Video Translation", "Streaming API"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "leonardo-ai",
    name: "Leonardo.ai",
    description: "Production-quality image assets.",
    longDescription: "Leonardo offers a suite of tools for game assets, architecture, and character design.",
    category: "image-generation",
    logo: generateLogo("Leonardo", "130F40"),
    link: "https://leonardo.ai",
    screenshots: [generateScreenshot("Leonardo")],
    launchDate: "2023-01-10T00:00:00Z",
    lastUpdated: "2025-02-20T00:00:00Z",
    isTrending: true,
    pricing: { model: "Freemium", details: "Daily free tokens." },
    features: ["Canvas editing", "Model training", "Live Gen"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "otter-ai-2025",
    name: "Otter.ai",
    description: "AI meeting notes and summaries.",
    longDescription: "Otter records and transcribes meetings in real-time with action item extraction.",
    category: "productivity",
    logo: generateLogo("Otter", "00AEEF"),
    link: "https://otter.ai",
    screenshots: [generateScreenshot("Otter")],
    launchDate: "2018-02-01T00:00:00Z",
    lastUpdated: "2025-02-25T00:00:00Z",
    isTrending: false,
    pricing: { model: "Freemium", details: "Pro for $10/mo." },
    features: ["Live Transcription", "OtterPilot", "Slack Integration"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "mem-ai-pro",
    name: "Mem",
    description: "The self-organizing workspace.",
    longDescription: "Mem uses AI to organize your notes, projects, and contacts automatically.",
    category: "productivity",
    logo: generateLogo("Mem", "FF4757"),
    link: "https://mem.ai",
    screenshots: [generateScreenshot("Mem AI")],
    launchDate: "2021-08-01T00:00:00Z",
    lastUpdated: "2025-01-15T00:00:00Z",
    isTrending: false,
    pricing: { model: "Freemium", details: "$15/mo for Mem X." },
    features: ["Smart Search", "Contextual Recall", "Mem It"],
    reviews: [],
    collections: [],
    noCode: true,
  },
  {
    id: "tabnine-v2",
    name: "Tabnine",
    description: "AI code completion for teams.",
    longDescription: "Tabnine provides private, secure AI code completions tailored to your team's code.",
    category: "code-assistant",
    logo: generateLogo("Tabnine", "2980B9"),
    link: "https://tabnine.com",
    screenshots: [generateScreenshot("Tabnine")],
    launchDate: "2018-01-01T00:00:00Z",
    lastUpdated: "2025-02-15T00:00:00Z",
    isTrending: false,
    pricing: { model: "Freemium", details: "$12/mo Pro." },
    features: ["Private Hosting", "Local Models", "Tailored Suggestions"],
    reviews: [],
    collections: [],
    noCode: false,
  }
];

export const collections: Collection[] = [
    {
      id: 'best-of-2025',
      name: 'Best of 2025',
      description: 'The most revolutionary AI tools defining the landscape this year.',
      toolIds: ['claude-3-5', 'openai-o3', 'flux-2', 'sora', 'udio-v2', 'gemini-2-ultra'],
    },
    {
      id: 'dev-stack',
      name: 'Modern AI Dev Stack',
      description: 'Essential AI tools for the modern software engineer.',
      toolIds: ['cursor', 'perplexity', 'claude-3-5', 'devin', 'replit-agent'],
    },
];

export const aiNews: NewsItem[] = [
    {
        id: "news-1",
        title: "DeepSeek-V3 Open Sourced: A New Era for Efficiency",
        summary: "The latest model from DeepSeek sets new benchmarks for cost-effective AI training and inference.",
        date: "2025-02-25",
        url: "#",
        source: "AI Daily"
    },
    {
        id: "news-2",
        title: "OpenAI Announces o3-mini Reasoning Model",
        summary: "A more compact but powerful version of the o3 series optimized for STEM and reasoning.",
        date: "2025-02-24",
        url: "#",
        source: "TechCrunch"
    },
    {
        id: "news-3",
        title: "Gemini 2.0 Ultra Claims Top Spot in Benchmarks",
        summary: "Google's latest flagship outshines competitors in multi-modal understanding and long-context reasoning.",
        date: "2025-02-22",
        url: "#",
        source: "Verge"
    }
];
